gethostdetails:
	gcc gethostdetails.c -o main && ./main

tcp_serv:
	gcc tcp_server.c -o main && ./main

tcp_client:
	gcc tcp_client.c -o main && ./main

udp_serv:
	gcc udp_server.c -o main && ./main

chat_serv:
	gcc chat_server.c -o main && ./main