gethostdetails:
	gcc gethostdetails.c -o main && ./main && rm main

tcp_serv:
	gcc tcp_server.c -o main && ./main && rm main

tcp_client:
	gcc tcp_client.c -o main && ./main && rm main

udp_serv:
	gcc udp_server.c -o main && ./main && rm main

chat_serv:
	gcc chat_server.c -o main && ./main && rm main

dual_stack_tcp_serv:
	gcc dual_stack_tcp_server.c -o main && ./main && rm main